Add profile expiration time to settings page
LoopKit/Loop pull request #1917
Opened 2023-01-31 19:34 UTC by Chris-Almond

Adding the ability for users to see when their profile expires without waiting for the pop-up warning modal message. 

This small enhancement gives users more visibility into the remaining life of their Loop app, to help them plan to rebuild and load fresh profiles.

### UI Before 

![beforeLight](https://user-images.githubusercontent.com/47440708/215862972-87759ea9-79c8-4050-bf0a-72d453ebecd1.jpg) 

### After changes

\> 3 Days Dark

 ![greaterThan3DaysDark](https://user-images.githubusercontent.com/47440708/215862993-e769efe7-880f-4d0a-9779-084fd030a9dd.jpg) 

\> 3 Days Light 

![greaterThan3DaysLight](https://user-images.githubusercontent.com/47440708/215862995-e411aca6-6a6a-40b5-9ab2-3c9615f24769.jpg) 

< 3 Days Dark 

![lessThan3DaysDark](https://user-images.githubusercontent.com/47440708/215862999-8cb86703-4e1d-4755-8413-2772642c357f.jpg) 

< 3 Days Light 

![lessThan3DaysLight](https://user-images.githubusercontent.com/47440708/215863000-bff28d6a-dd83-4b66-9c7c-32471a942c10.jpg)

2023-01-31 21:40 UTC, ps2 commented
Nice! Profile Expiration and LoopDocs are DIY Loop specific things, so it should probably live in LoopSupport, which is a DIY Plugin. If you can move it there, I'd be happy to accept this PR. Another option would be to put it behind a feature flag.

2023-01-31 21:45 UTC, ps2 requested changes
Nice! Profile Expiration and LoopDocs are DIY Loop specific things, so it should probably live in LoopSupport, which is a DIY Plugin. If you can move it there, I'd be happy to accept this PR. Another option would be to put it behind a feature flag.

2023-02-02 07:15 UTC, Chris-Almond commented
Added a feature flag `PROFILE_EXPIRATION_SETTINGS_VIEW_ENABLED` in the latest commit with the default as disabled. 

1. How does this look?
2. Do you prefer I squash these commits together myself (or will GitHub handle that during the merge)?
3. Do you want me to create a PR adding this flag in a commented out state to `LoopWorkspace`'s `LoopConfigOverride.xcconfig`? If so, any specific branch I should target? (sample change below)
```
 // Features
-SWIFT_ACTIVE_COMPILATION_CONDITIONS = $(inherited) SIMULATORS_ENABLED //DEBUG_FEATURES_ENABLED
+SWIFT_ACTIVE_COMPILATION_CONDITIONS = $(inherited) SIMULATORS_ENABLED //PROFILE_EXPIRATION_SETTINGS_VIEW_ENABLED //DEBUG_FEATURES_ENABLED
```

2023-02-03 18:33 UTC, ps2 commented
I can squash commits during merge, thanks.  Generally the default state is the DIY state, so I think the flag should be such that without any extra compilation conditions, the profile UI is shown. And we can add the flag to disable it in builds where it shouldn't be shown, so you would not need to submit a Workspace PR.

2023-02-04 01:31 UTC, Chris-Almond commented
Sounds great. Thanks. 

Ok, so my action item is to invert the flag to let the default be enabled. 

Anything else or good to go after that?

2023-02-05 23:56 UTC, Chris-Almond reviewed
Inverted the feature flag so the default is enabled. 

Also squashed a tiny rendering bug that shows hours when days remaining > 3 and hours == 0.

2023-02-07 22:42 UTC, merged